// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textfile.proto

#include "textfile.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Files {
PROTOBUF_CONSTEXPR Project::Project(
    ::_pbi::ConstantInitialized)
  : filename_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , creater_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , createdtime_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , modifiedtime_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , projectid_(0)
  , currentversion_(0){}
struct ProjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProjectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProjectDefaultTypeInternal() {}
  union {
    Project _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProjectDefaultTypeInternal _Project_default_instance_;
PROTOBUF_CONSTEXPR ProjectList::ProjectList(
    ::_pbi::ConstantInitialized)
  : projectnamelist_()
  , count_(0){}
struct ProjectListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProjectListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProjectListDefaultTypeInternal() {}
  union {
    ProjectList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProjectListDefaultTypeInternal _ProjectList_default_instance_;
}  // namespace Files
static ::_pb::Metadata file_level_metadata_textfile_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_textfile_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_textfile_2eproto = nullptr;

const uint32_t TableStruct_textfile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Files::Project, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Files::Project, projectid_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, currentversion_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, filename_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, creater_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, createdtime_),
  PROTOBUF_FIELD_OFFSET(::Files::Project, modifiedtime_),
  4,
  5,
  0,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::Files::ProjectList, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Files::ProjectList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Files::ProjectList, projectnamelist_),
  PROTOBUF_FIELD_OFFSET(::Files::ProjectList, count_),
  ~0u,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, -1, sizeof(::Files::Project)},
  { 18, 26, -1, sizeof(::Files::ProjectList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Files::_Project_default_instance_._instance,
  &::Files::_ProjectList_default_instance_._instance,
};

const char descriptor_table_protodef_textfile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016textfile.proto\022\005Files\"\373\001\n\007Project\022\026\n\tp"
  "rojectId\030\001 \001(\005H\000\210\001\001\022\033\n\016currentVersion\030\002 "
  "\001(\005H\001\210\001\001\022\025\n\010fileName\030\003 \001(\tH\002\210\001\001\022\024\n\007creat"
  "er\030\004 \001(\tH\003\210\001\001\022\030\n\013createdTime\030\005 \001(\tH\004\210\001\001\022"
  "\031\n\014ModifiedTime\030\006 \001(\tH\005\210\001\001B\014\n\n_projectId"
  "B\021\n\017_currentVersionB\013\n\t_fileNameB\n\n\010_cre"
  "aterB\016\n\014_createdTimeB\017\n\r_ModifiedTime\"T\n"
  "\013ProjectList\022\'\n\017projectNameList\030\001 \003(\0132\016."
  "Files.Project\022\022\n\005count\030\002 \001(\005H\000\210\001\001B\010\n\006_co"
  "untb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_textfile_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_textfile_2eproto = {
    false, false, 371, descriptor_table_protodef_textfile_2eproto,
    "textfile.proto",
    &descriptor_table_textfile_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_textfile_2eproto::offsets,
    file_level_metadata_textfile_2eproto, file_level_enum_descriptors_textfile_2eproto,
    file_level_service_descriptors_textfile_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_textfile_2eproto_getter() {
  return &descriptor_table_textfile_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_textfile_2eproto(&descriptor_table_textfile_2eproto);
namespace Files {

// ===================================================================

class Project::_Internal {
 public:
  using HasBits = decltype(std::declval<Project>()._has_bits_);
  static void set_has_projectid(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_currentversion(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_filename(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_creater(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_createdtime(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_modifiedtime(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

Project::Project(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Files.Project)
}
Project::Project(const Project& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_filename()) {
    filename_.Set(from._internal_filename(), 
      GetArenaForAllocation());
  }
  creater_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    creater_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_creater()) {
    creater_.Set(from._internal_creater(), 
      GetArenaForAllocation());
  }
  createdtime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    createdtime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_createdtime()) {
    createdtime_.Set(from._internal_createdtime(), 
      GetArenaForAllocation());
  }
  modifiedtime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    modifiedtime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_modifiedtime()) {
    modifiedtime_.Set(from._internal_modifiedtime(), 
      GetArenaForAllocation());
  }
  ::memcpy(&projectid_, &from.projectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&currentversion_) -
    reinterpret_cast<char*>(&projectid_)) + sizeof(currentversion_));
  // @@protoc_insertion_point(copy_constructor:Files.Project)
}

inline void Project::SharedCtor() {
filename_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  filename_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
creater_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  creater_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
createdtime_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  createdtime_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
modifiedtime_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  modifiedtime_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&projectid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&currentversion_) -
    reinterpret_cast<char*>(&projectid_)) + sizeof(currentversion_));
}

Project::~Project() {
  // @@protoc_insertion_point(destructor:Files.Project)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Project::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  filename_.Destroy();
  creater_.Destroy();
  createdtime_.Destroy();
  modifiedtime_.Destroy();
}

void Project::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Project::Clear() {
// @@protoc_insertion_point(message_clear_start:Files.Project)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      filename_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      creater_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      createdtime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      modifiedtime_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000030u) {
    ::memset(&projectid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&currentversion_) -
        reinterpret_cast<char*>(&projectid_)) + sizeof(currentversion_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Project::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 projectId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_projectid(&has_bits);
          projectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 currentVersion = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_currentversion(&has_bits);
          currentversion_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string fileName = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Files.Project.fileName"));
        } else
          goto handle_unusual;
        continue;
      // optional string creater = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_creater();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Files.Project.creater"));
        } else
          goto handle_unusual;
        continue;
      // optional string createdTime = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_createdtime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Files.Project.createdTime"));
        } else
          goto handle_unusual;
        continue;
      // optional string ModifiedTime = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_modifiedtime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Files.Project.ModifiedTime"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Project::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Files.Project)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional int32 projectId = 1;
  if (_internal_has_projectid()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_projectid(), target);
  }

  // optional int32 currentVersion = 2;
  if (_internal_has_currentversion()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_currentversion(), target);
  }

  // optional string fileName = 3;
  if (_internal_has_filename()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Files.Project.fileName");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_filename(), target);
  }

  // optional string creater = 4;
  if (_internal_has_creater()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_creater().data(), static_cast<int>(this->_internal_creater().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Files.Project.creater");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_creater(), target);
  }

  // optional string createdTime = 5;
  if (_internal_has_createdtime()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_createdtime().data(), static_cast<int>(this->_internal_createdtime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Files.Project.createdTime");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_createdtime(), target);
  }

  // optional string ModifiedTime = 6;
  if (_internal_has_modifiedtime()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_modifiedtime().data(), static_cast<int>(this->_internal_modifiedtime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Files.Project.ModifiedTime");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_modifiedtime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Files.Project)
  return target;
}

size_t Project::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Files.Project)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string fileName = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_filename());
    }

    // optional string creater = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_creater());
    }

    // optional string createdTime = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_createdtime());
    }

    // optional string ModifiedTime = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_modifiedtime());
    }

    // optional int32 projectId = 1;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_projectid());
    }

    // optional int32 currentVersion = 2;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_currentversion());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Project::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Project::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Project::GetClassData() const { return &_class_data_; }

void Project::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Project *>(to)->MergeFrom(
      static_cast<const Project &>(from));
}


void Project::MergeFrom(const Project& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Files.Project)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_filename(from._internal_filename());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_creater(from._internal_creater());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_createdtime(from._internal_createdtime());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_set_modifiedtime(from._internal_modifiedtime());
    }
    if (cached_has_bits & 0x00000010u) {
      projectid_ = from.projectid_;
    }
    if (cached_has_bits & 0x00000020u) {
      currentversion_ = from.currentversion_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Project::CopyFrom(const Project& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Files.Project)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Project::IsInitialized() const {
  return true;
}

void Project::InternalSwap(Project* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &filename_, lhs_arena,
      &other->filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &creater_, lhs_arena,
      &other->creater_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &createdtime_, lhs_arena,
      &other->createdtime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &modifiedtime_, lhs_arena,
      &other->modifiedtime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Project, currentversion_)
      + sizeof(Project::currentversion_)
      - PROTOBUF_FIELD_OFFSET(Project, projectid_)>(
          reinterpret_cast<char*>(&projectid_),
          reinterpret_cast<char*>(&other->projectid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Project::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_textfile_2eproto_getter, &descriptor_table_textfile_2eproto_once,
      file_level_metadata_textfile_2eproto[0]);
}

// ===================================================================

class ProjectList::_Internal {
 public:
  using HasBits = decltype(std::declval<ProjectList>()._has_bits_);
  static void set_has_count(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ProjectList::ProjectList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  projectnamelist_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Files.ProjectList)
}
ProjectList::ProjectList(const ProjectList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      projectnamelist_(from.projectnamelist_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  count_ = from.count_;
  // @@protoc_insertion_point(copy_constructor:Files.ProjectList)
}

inline void ProjectList::SharedCtor() {
count_ = 0;
}

ProjectList::~ProjectList() {
  // @@protoc_insertion_point(destructor:Files.ProjectList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProjectList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProjectList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ProjectList::Clear() {
// @@protoc_insertion_point(message_clear_start:Files.ProjectList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  projectnamelist_.Clear();
  count_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProjectList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Files.Project projectNameList = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_projectnamelist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional int32 count = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_count(&has_bits);
          count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProjectList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Files.ProjectList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Files.Project projectNameList = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_projectnamelist_size()); i < n; i++) {
    const auto& repfield = this->_internal_projectnamelist(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional int32 count = 2;
  if (_internal_has_count()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Files.ProjectList)
  return target;
}

size_t ProjectList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Files.ProjectList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Files.Project projectNameList = 1;
  total_size += 1UL * this->_internal_projectnamelist_size();
  for (const auto& msg : this->projectnamelist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional int32 count = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProjectList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProjectList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProjectList::GetClassData() const { return &_class_data_; }

void ProjectList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ProjectList *>(to)->MergeFrom(
      static_cast<const ProjectList &>(from));
}


void ProjectList::MergeFrom(const ProjectList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Files.ProjectList)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  projectnamelist_.MergeFrom(from.projectnamelist_);
  if (from._internal_has_count()) {
    _internal_set_count(from._internal_count());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProjectList::CopyFrom(const ProjectList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Files.ProjectList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProjectList::IsInitialized() const {
  return true;
}

void ProjectList::InternalSwap(ProjectList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  projectnamelist_.InternalSwap(&other->projectnamelist_);
  swap(count_, other->count_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProjectList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_textfile_2eproto_getter, &descriptor_table_textfile_2eproto_once,
      file_level_metadata_textfile_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Files
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Files::Project*
Arena::CreateMaybeMessage< ::Files::Project >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Files::Project >(arena);
}
template<> PROTOBUF_NOINLINE ::Files::ProjectList*
Arena::CreateMaybeMessage< ::Files::ProjectList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Files::ProjectList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
